# Generated by Django 5.1.5 on 2025-02-17 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital', '0002_father_mother_newborn'),
    ]

    operations = [
        migrations.AddField(
            model_name='newborn',
            name='allaitement',
            field=models.CharField(blank=True, choices=[('maternel', 'Allaitement maternel'), ('artificiel', 'Allaitement artificiel'), ('mixte', 'Mixte')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='newborn',
            name='antecedents_familiaux',
            field=models.TextField(blank=True, help_text='Antécédents médicaux familiaux importants', null=True),
        ),
        migrations.AddField(
            model_name='newborn',
            name='complications',
            field=models.TextField(blank=True, help_text='Complications éventuelles', null=True),
        ),
        migrations.AddField(
            model_name='newborn',
            name='date_sortie',
            field=models.DateField(blank=True, help_text="Date de sortie de l'hôpital", null=True),
        ),
        migrations.AddField(
            model_name='newborn',
            name='duree_travail',
            field=models.DurationField(blank=True, help_text="Durée du travail avant l'accouchement", null=True),
        ),
        migrations.AddField(
            model_name='newborn',
            name='frequence_cardiaque',
            field=models.IntegerField(blank=True, help_text='Fréquence cardiaque du bébé (battements par minute)', null=True),
        ),
        migrations.AddField(
            model_name='newborn',
            name='frequence_respiratoire',
            field=models.IntegerField(blank=True, help_text='Fréquence respiratoire (respirations par minute)', null=True),
        ),
        migrations.AddField(
            model_name='newborn',
            name='groupe_sanguin',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='newborn',
            name='heure_naissance',
            field=models.TimeField(blank=True, help_text='Heure de naissance', null=True),
        ),
        migrations.AddField(
            model_name='newborn',
            name='lieu_naissance',
            field=models.CharField(choices=[('hopital', 'Hôpital'), ('clinique', 'Clinique'), ('domicile', 'Domicile')], default='hopital', max_length=20),
        ),
        migrations.AddField(
            model_name='newborn',
            name='reanimation',
            field=models.BooleanField(default=False, help_text='Réanimation nécessaire après la naissance ?'),
        ),
        migrations.AddField(
            model_name='newborn',
            name='score_apgar_10min',
            field=models.IntegerField(blank=True, help_text='Score APGAR à 10 min (0-10)', null=True),
        ),
        migrations.AddField(
            model_name='newborn',
            name='score_apgar_1min',
            field=models.IntegerField(blank=True, help_text='Score APGAR à 1 min (0-10)', null=True),
        ),
        migrations.AddField(
            model_name='newborn',
            name='score_apgar_5min',
            field=models.IntegerField(blank=True, help_text='Score APGAR à 5 min (0-10)', null=True),
        ),
        migrations.AddField(
            model_name='newborn',
            name='type_accouchement',
            field=models.CharField(choices=[('voie_basse', 'Accouchement par voie basse'), ('cesarienne', 'Césarienne'), ('forceps', 'Forceps ou ventouse')], default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newborn',
            name='vaccins',
            field=models.TextField(blank=True, help_text='Vaccins administrés à la naissance', null=True),
        ),
    ]
