# Generated by Django 5.1.5 on 2025-02-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital', '0003_newborn_allaitement_newborn_antecedents_familiaux_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('categorie', models.CharField(choices=[('antibiotique', 'Antibiotique'), ('antalgique', 'Antalgique'), ('anti-inflammatoire', 'Anti-inflammatoire'), ('vitamines', 'Vitamines'), ('autres', 'Autres')], max_length=100)),
                ('quantite_stock', models.PositiveIntegerField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_expiration', models.DateField()),
            ],
        ),
    ]
