# Generated by Django 5.1.5 on 2025-02-19 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hopital', '0004_medicament'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='email',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='adresse',
            field=models.TextField(blank=True, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='mobile',
            field=models.CharField(max_length=15, unique=True, verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nom du médecin'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialite',
            field=models.CharField(max_length=100, verbose_name='Spécialité'),
        ),
    ]
